### ISSUE TITLE
About release scheme

### ISSUE THREAD

**Issue by chenrui333** [h26forge/h26forge#9]
👋 I am reviewing [this h26forge homebrew PR](https://github.com/Homebrew/homebrew-core/pull/175923), I saw the releases are actually using `latest-<git sha>`, would it be possible to adopt CalVer rather than that? Thanks!

**Comment by wrv** [comment]
Awesome! Yes, I'm happy to help. Would something like `latest-YYYY-mm` be okay?

**Comment by chenrui333** [comment]
can we just do 2024-07-06?
